#!/usr/bin/env bash

include var.make

#######################################
# BUILD
#######################################

.PHONY: build_debug
build_debug:	${DIR_BUILD_DEBUG}/${APP_NAME}

${DIR_BUILD_DEBUG}/${APP_NAME}:	${SRC}
	@cd ${DIR_BUILD_DEBUG} && cmake -DCMAKE_BUILD_TYPE=Debug ../..
	@make -C ${DIR_BUILD_DEBUG}

.PHONY: build_release
build_release:	${DIR_BUILD_RELEASE}/${APP_NAME}

${DIR_BUILD_RELEASE}/${APP_NAME}:	${SRC}
	@cd ${DIR_BUILD_RELEASE} && cmake -DCMAKE_BUILD_TYPE=Debug ../..
	@make -C ${DIR_BUILD_RELEASE}

.PHONY: build_maxopt
build_maxopt:	${DIR_BUILD_MAXOPT}/${APP_NAME}

${DIR_BUILD_MAXOPT}/${APP_NAME}:	${SRC}
	@cd ${DIR_BUILD_MAXOPT} && \
		cmake -DCMAKE_CXX_FLAGS="${DCMAKE_CXX_FLAGS} -Ofast -march=native" ../..
	@make -C ${DIR_BUILD_MAXOPT}

#######################################
# RUN
#######################################

.PHONY: release
release:	build_release
	@cd ${DIR_BUILD}/$@ && ./${APP_NAME}

.PHONY: debug
debug:		build_debug
	@cd ${DIR_BUILD}/$@ && ./${APP_NAME}

.PHONY: maxopt
maxopt:		build_maxopt
	@cd ${DIR_BUILD}/$@ && ./${APP_NAME}

# vim: ft=make
